DROP DATABASE IF EXISTS ci_email;
CREATE DATABASE IF NOT EXISTS ci_email DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE ci_email;

DROP TABLE IF EXISTS usuarios;
CREATE TABLE IF NOT EXISTS usuarios(
	id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL COLLATE utf8_spanish_ci,
	correo VARCHAR(100) NOT NULL,
	nick VARCHAR(50) NOT NULL,
	password VARCHAR(20) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
