DROP DATABASE IF EXISTS bg_manager;
CREATE DATABASE IF NOT EXISTS bg_manager DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE bg_manager;

DROP TABLE IF EXISTS comentarios;
CREATE TABLE IF NOT EXISTS comentarios(
	codigo_comentario INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	tabla_origen_comentario VARCHAR(20) NULL DEFAULT NULL,
	codigo_tabla_origen_comentario INT(10) UNSIGNED NULL DEFAULT NULL,
	comentario TEXT NULL DEFAULT NULL COLLATE utf8_spanish_ci,
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL,
	INDEX fk_comentarios_personas_idx(codigo_comentario ASC),
	INDEX fk_comentarios_preferencias_idx(codigo_comentario ASC),
	INDEX fk_comentarios_pedidos_idx(codigo_comentario ASC),
	INDEX fk_comentarios_articulos_idx(codigo_comentario ASC),
	INDEX fk_comentarios_tiendas_idx(codigo_comentario ASC),
	CONSTRAINT fk_comentarios_personas FOREIGN KEY(codigo_comentario) REFERENCES personas(codigo_comentario) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_comentarios_preferencias FOREIGN KEY(codigo_comentario) REFERENCES preferencias(codigo_comentario) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_comentarios_pedidos FOREIGN KEY(codigo_comentario) REFERENCES pedidos(codigo_comentario) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_comentarios_articulos FOREIGN KEY(codigo_comentario) REFERENCES articulos(codigo_comentario) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_comentarios_tiendas FOREIGN KEY(codigo_comentario) REFERENCES tiendas(codigo_comentario) ON DELETE CASCADE ON UPDATE CASCADE	
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS telefonos;
CREATE TABLE IF NOT EXISTS telefonos(
	codigo_telefono INT(2) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	numero_telefono VARCHAR(8) NOT NULL COMMENT 'Sin guión',
	codigo_persona INT(2) UNSIGNED NULL DEFAULT NULL COMMENT 'De cero a muchos Telefonos pertenecen a una Persona',
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL,
	INDEX fk_telefonos_personas_idx(codigo_persona ASC),
	CONSTRAINT fk_telefonos_personas FOREIGN KEY(codigo_persona) REFERENCES personas(codigo_persona) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS departamentos;
CREATE TABLE IF NOT EXISTS departamentos(
	codigo_departamento INT(2) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre_departamento VARCHAR(50) NOT NULL COLLATE utf8_spanish_ci,
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS municipios;
CREATE TABLE IF NOT EXISTS municipios(
	codigo_municipio INT(3) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre_municipio VARCHAR(50) NOT NULL COLLATE utf8_spanish_ci,
	codigo_departamento INT(2) UNSIGNED NOT NULL,
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL,
	INDEX fk_municipios_departamentos_idx(codigo_departamento ASC),
	CONSTRAINT fk_municipios_departamentos FOREIGN KEY(codigo_departamento) REFERENCES departamentos(codigo_departamento) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS personas;
CREATE TABLE IF NOT EXISTS personas(
	codigo_persona INT(5) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombres_persona VARCHAR(50) NOT NULL COLLATE utf8_spanish_ci,
	apellidos_persona VARCHAR(50) NOT NULL COLLATE utf8_spanish_ci,
	apodo_persona VARCHAR(20) NULL DEFAULT NULL COLLATE utf8_spanish_ci,
	dui_persona VARCHAR(9) NULL DEFAULT NULL COMMENT 'Sin guión',
	sexo_persona VARCHAR(6) NULL DEFAULT NULL COMMENT 'Mujer, Hombre',
	correo_electronico_persona VARCHAR(50) NULL DEFAULT NULL,
	facebook_persona VARCHAR(50) NULL DEFAULT NULL,
	codigo_departamento INT(2) UNSIGNED NULL DEFAULT NULL,
	codigo_municipio INT(3) UNSIGNED NULL DEFAULT NULL,
	codigo_comentario INT(10) UNSIGNED NULL DEFAULT NULL,
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL,
	INDEX fk_personas_departamentos_idx(codigo_departamento ASC),
	INDEX fk_personas_municipios_permisos_idx(codigo_municipio ASC),
	INDEX fk_personas_comentarios_idx(codigo_comentario ASC),
	CONSTRAINT fk_personas_departamentos FOREIGN KEY(codigo_departamento) REFERENCES departamentos(codigo_departamento) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_personas_municipios FOREIGN KEY(codigo_municipio) REFERENCES municipios(codigo_municipio) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_personas_comentarios FOREIGN KEY(codigo_comentario) REFERENCES comentarios(codigo_comentario) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS usuarios;
CREATE TABLE IF NOT EXISTS usuarios(
	codigo_usuario INT(5) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre_usuario VARCHAR(50) NOT NULL,
	password_usuario VARCHAR(50) NULL DEFAULT NULL,
	fecha_expiracion_usuario DATETIME NULL DEFAULT NULL,
	bloqueado_usuario BOOLEAN NOT NULL DEFAULT FALSE,
	razon_bloqueado_usuario VARCHAR(255) NULL DEFAULT NULL COLLATE utf8_spanish_ci,
	reiniciar_password_usuario BOOLEAN NOT NULL DEFAULT TRUE,
	inactivo_usuario BOOLEAN NOT NULL DEFAULT FALSE,
	ultima_fecha_sesion_usuario DATETIME NULL DEFAULT NULL,
	codigo_persona INT(5) UNSIGNED NULL DEFAULT NULL COMMENT 'De cero a muchos Usuarios pertenecen a una Persona',
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL,
	INDEX fk_usuarios_personas_idx(codigo_persona ASC),
	CONSTRAINT fk_usuarios_personas FOREIGN KEY(codigo_persona) REFERENCES personas(codigo_persona) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS roles;
CREATE TABLE IF NOT EXISTS roles(
	codigo_rol INT(5) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre_rol VARCHAR(50) NOT NULL,
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS permisos;
CREATE TABLE IF NOT EXISTS permisos(
	codigo_permiso INT(5) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre_permiso VARCHAR(50) NOT NULL,
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS roles_permisos;
CREATE TABLE IF NOT EXISTS roles_permisos(
	codigo_rol_permiso INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	consultar TINYINT(1) NULL DEFAULT 0,
	agregar TINYINT(1) NULL DEFAULT 0,
	editar TINYINT(1) NULL DEFAULT 0,
	eliminar TINYINT(1) NULL DEFAULT 0,
	codigo_rol INT(5) UNSIGNED NOT NULL COMMENT 'Un Rol puede tener de uno a muchos Permisos',
	codigo_permiso INT(5) UNSIGNED NOT NULL COMMENT 'Un Permiso puede tener de uno a muchos Roles',
	INDEX fk_roles_permisos_roles_idx(codigo_rol ASC),
	INDEX fk_roles_permisos_permisos_idx(codigo_permiso ASC),
	CONSTRAINT fk_roles_permisos_roles FOREIGN KEY(codigo_rol) REFERENCES roles(codigo_rol) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT fk_roles_permisos_permisos FOREIGN KEY(codigo_permiso) REFERENCES permisos(codigo_permiso) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 COMMENT 'Relación de uno a muchos Roles a uno a muchos Permisos';

DROP TABLE IF EXISTS usuarios_roles;
CREATE TABLE IF NOT EXISTS usuarios_roles(
	codigo_usuario_rol INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	codigo_usuario INT(5) UNSIGNED NOT NULL COMMENT 'Un Usuario puede tener de uno a muchos Roles',
	codigo_rol INT(5) UNSIGNED NOT NULL COMMENT 'Un Rol puede tener de uno a muchos Usuarios',
	INDEX fk_usuarios_roles_usuarios_idx(codigo_usuario ASC),
	INDEX fk_usuarios_roles_roles_idx(codigo_rol ASC),
	CONSTRAINT fk_usuarios_roles_usuarios FOREIGN KEY(codigo_usuario) REFERENCES usuarios(codigo_usuario) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT fk_usuarios_roles_roles FOREIGN KEY(codigo_rol) REFERENCES roles(codigo_rol) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 COMMENT 'Relación de uno a muchos Usuarios a uno a muchos Roles';

DROP TABLE IF EXISTS preferencias;
CREATE TABLE IF NOT EXISTS preferencias(
	codigo_preferencia INT(2) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	talla_preferencia VARCHAR(10) NULL DEFAULT NULL COMMENT 'Talla promedio (depende del historial de pedidos)',
	color_preferencia VARCHAR(10) NULL DEFAULT NULL COMMENT 'Color promedio (depende del historial de pedidos)',
	codigo_tipo_articulo INT(5) UNSIGNED NOT NULL,
	codigo_comentario INT(10) UNSIGNED NULL DEFAULT NULL,
	codigo_persona INT(5) UNSIGNED NOT NULL COMMENT 'Muchas Preferencias pertenecen a una Persona',
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL,
	INDEX fk_preferencias_tipos_articulos_idx(codigo_tipo_articulo ASC),
	INDEX fk_preferencias_comentarios_idx(codigo_comentario ASC),
	INDEX fk_preferencias_personas_idx(codigo_persona ASC),
	CONSTRAINT fk_preferencias_tipos_articulos FOREIGN KEY(codigo_tipo_articulo) REFERENCES tipos_articulos(codigo_tipo_articulo) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_preferencias_comentarios FOREIGN KEY(codigo_comentario) REFERENCES comentarios(codigo_comentario) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_preferencias_personas FOREIGN KEY(codigo_persona) REFERENCES personas(codigo_persona) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 COMMENT 'Preferencias de los Clientes (Personas)';

DROP TABLE IF EXISTS pedidos;
CREATE TABLE IF NOT EXISTS pedidos(
	codigo_pedido INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	fecha_pedido DATETIME NOT NULL,
	fecha_entrega_pedido DATETIME NOT NULL,
	lugar_entrega_pedido VARCHAR(50) NOT NULL COLLATE utf8_spanish_ci,
	cantidad_pedido INT(3) NOT NULL COMMENT 'Sumatoria de todos los cantidad_pedido_articulo',
	monto_pedido FLOAT(3, 2) NOT NULL COMMENT 'Sumatoria de todos los monto_pedido_articulo',
	codigo_persona INT(5) UNSIGNED NOT NULL COMMENT 'Muchos Pedidos pertenecen a una Persona',
	codigo_comentario INT(10) UNSIGNED NULL DEFAULT NULL,
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL,
	INDEX fk_pedidos_personas_idx(codigo_persona ASC),
	INDEX fk_pedidos_comentarios_idx(codigo_comentario ASC),
	CONSTRAINT fk_pedidos_personas FOREIGN KEY(codigo_persona) REFERENCES personas(codigo_persona) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_pedidos_comentarios FOREIGN KEY(codigo_comentario) REFERENCES comentarios(codigo_comentario) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS tipos_articulos;
CREATE TABLE IF NOT EXISTS tipos_articulos(
	codigo_tipo_articulo INT(2) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre_tipo_articulo VARCHAR(8) NOT NULL,
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS articulos;
CREATE TABLE IF NOT EXISTS articulos(
	codigo_articulo INT(5) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre_articulo VARCHAR(50) NULL DEFAULT NULL COLLATE utf8_spanish_ci,
	estilo_articulo VARCHAR(20) NULL DEFAULT NULL COLLATE utf8_spanish_ci,
	talla_articulo VARCHAR(10) NOT NULL COLLATE utf8_spanish_ci,
	color_articulo VARCHAR(10) NOT NULL COLLATE utf8_spanish_ci,
	marca_articulo VARCHAR(20) NULL DEFAULT NULL COLLATE utf8_spanish_ci,
	cantidad_articulo INT(2) NOT NULL COMMENT 'cantidad_articulo - cantidad_pedido_articulo',
	precio_compra_articulo FLOAT(3, 2) NOT NULL,
	precio_venta_articulo FLOAT(3, 2) NOT NULL,
	codigo_tipo_articulo INT(5) UNSIGNED NOT NULL COMMENT 'Muchos Articulos pertenecen un Tipo de Articulo',
	codigo_comentario INT(10) UNSIGNED NULL DEFAULT NULL,
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL,
	INDEX fk_articulos_tipos_articulos_idx(codigo_tipo_articulo ASC),
	INDEX fk_articulos_comentarios_idx(codigo_comentario ASC),
	CONSTRAINT fk_articulos_tipos_articulos FOREIGN KEY(codigo_tipo_articulo) REFERENCES tipos_articulos(codigo_tipo_articulo) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_articulos_comentarios FOREIGN KEY(codigo_comentario) REFERENCES comentarios(codigo_comentario) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS pedidos_articulos;
CREATE TABLE IF NOT EXISTS pedidos_articulos(
	codigo_pedido_articulo INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cantidad_pedido_articulo INT(3) NOT NULL,
	monto_pedido_articulo FLOAT(3, 2) NOT NULL COMMENT 'cantidad_pedido_articulo * precio_venta_articulo',
	codigo_pedido INT(5) UNSIGNED NOT NULL COMMENT 'Un Pedido (Factura) puede tener de uno a muchos Articulos',
	codigo_articulo INT(5) UNSIGNED NOT NULL COMMENT 'Un Articulo puede estar de uno a muchos Pedidos',
	INDEX fk_pedidos_articulos_pedidos_idx(codigo_pedido ASC),
	INDEX fk_pedidos_articulos_articulos_idx(codigo_articulo ASC),
	CONSTRAINT fk_pedidos_articulos_pedidos FOREIGN KEY(codigo_pedido) REFERENCES pedidos(codigo_pedido) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_pedidos_articulos_articulos FOREIGN KEY(codigo_articulo) REFERENCES articulos(codigo_articulo) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 COMMENT 'Relación de uno a muchos Pedidos a uno a muchos Articulos';

DROP TABLE IF EXISTS tiendas;
CREATE TABLE IF NOT EXISTS tiendas(
	codigo_tienda INT(5) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre_tienda VARCHAR(50) NOT NULL COLLATE utf8_spanish_ci,
	estilo_tienda VARCHAR(20) NULL DEFAULT NULL COLLATE utf8_spanish_ci,
	direccion_tienda VARCHAR(100) NULL DEFAULT NULL COLLATE utf8_spanish_ci,
	codigo_departamento INT(5) UNSIGNED NULL DEFAULT NULL,
	codigo_municipio INT(5) UNSIGNED NULL DEFAULT NULL,
	codigo_comentario INT(10) UNSIGNED NULL DEFAULT NULL,
	modificado_por VARCHAR(50) NULL DEFAULT NULL,
	ultima_modificacion DATETIME NULL DEFAULT NULL,
	INDEX fk_tiendas_departamentos_idx(codigo_departamento ASC),
	INDEX fk_tiendas_municipios_idx(codigo_municipio ASC),
	INDEX fk_tiendas_comentarios_idx(codigo_comentario ASC),
	CONSTRAINT fk_tiendas_departamentos FOREIGN KEY(codigo_departamento) REFERENCES departamentos(codigo_departamento) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_tiendas_municipios FOREIGN KEY(codigo_municipio) REFERENCES municipios(codigo_municipio) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_tiendas_comentarios FOREIGN KEY(codigo_comentario) REFERENCES comentarios(codigo_comentario) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

DROP TABLE IF EXISTS articulos_tiendas;
CREATE TABLE IF NOT EXISTS articulos_tiendas(
	codigo_articulo_tienda INT(5) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	codigo_articulo INT(5) UNSIGNED NOT NULL COMMENT 'Un Articulo puede tener de uno a muchos Tiendas',
	codigo_tienda INT(5) UNSIGNED NOT NULL COMMENT 'Una Tienda (Proveedor) puede tener de uno a muchos Articulos',
	INDEX fk_articulos_tiendas_articulos_idx(codigo_articulo ASC),
	INDEX fk_articulos_tiendas_tiendas_idx(codigo_tienda ASC),
	CONSTRAINT fk_articulos_tiendas_articulos FOREIGN KEY(codigo_articulo) REFERENCES articulos(codigo_articulo) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_articulos_tiendas_tiendas FOREIGN KEY(codigo_tienda) REFERENCES tiendas(codigo_tienda) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 COMMENT 'Relación de uno a muchos Articulos a uno a muchos Tiendas';

-- ============================================================================================================================================================

INSERT INTO departamentos(codigo_departamento, nombre_departamento) VALUES
(1, 'Ahuachapan'),
(2, 'Santa Ana'),
(3, 'Sonsonate'),
(4, 'Chalatenango'),
(5, 'Cuscatlan'),
(6, 'San Salvador'),
(7, 'La Libertad'),
(8, 'San Vicente'),
(9, 'La Paz'),
(10, 'Cabañas'),
(11, 'Usulutan'),
(12, 'San Miguel'),
(13, 'Morazan'),
(14, 'La Unión');

INSERT INTO municipios(codigo_municipio, codigo_departamento, nombre_municipio) VALUES
(1, 1, 'Ahuachapan'),
(2, 1, 'Jujutla'),
(3, 1, 'Atiquizaya'),
(4, 1, 'Concepción de Ataco'),
(5, 1, 'El Refugio'),
(6, 1, 'Guaymango'),
(7, 1, 'Apaneca'),
(8, 1, 'San Francisco Menendez'),
(9, 1, 'San Lorenzo'),
(10, 1, 'San Pedro Puxtla'),
(11, 1, 'Tacuba'),
(12, 1, 'Turín'),
(13, 2, 'Candelaria de la Frontera'),
(14, 2, 'Chalchuapa'),
(15, 2, 'Coatepeque'),
(16, 2, 'El Congo'),
(17, 2, 'El Porvenir'),
(18, 2, 'Masahuat'),
(19, 2, 'Metapan'),
(20, 2, 'San Antonio Pajonal'),
(21, 2, 'San Sebastian Salitrillo'),
(22, 2, 'Santa Ana'),
(23, 2, 'Santa Rosa Guachipilín'),
(24, 2, 'Santiago de la Frontera'),
(25, 2, 'Texistepeque'),
(26, 3, 'Acajutla'),
(27, 3, 'Armenia'),
(28, 3, 'Caluco'),
(29, 3, 'Cuisnahuat'),
(30, 3, 'Izalco'),
(31, 3, 'Juayua'),
(32, 3, 'Nahuizalco'),
(33, 3, 'Nahulingo'),
(34, 3, 'Salcoatitan'),
(35, 3, 'San Antonio del Monte'),
(36, 3, 'San Julian'),
(37, 3, 'Santa Catarina Masahuat'),
(38, 3, 'Santa Isabel Ishuatan'),
(39, 3, 'Santo Domingo'),
(40, 3, 'Sonsonate'),
(41, 3, 'Sonzacate'),
(42, 4, 'Agua Caliente'),
(43, 4, 'Arcatao'),
(44, 4, 'Azacualpa'),
(45, 4, 'Chalatenango'),
(46, 4, 'Citala'),
(47, 4, 'Comalapa'),
(48, 4, 'Concepción Quezaltepeque'),
(49, 4, 'Dulce Nombre de Maria'),
(50, 4, 'El Carrizal'),
(51, 4, 'El Paraiso'),
(52, 4, 'La Laguna'),
(53, 4, 'La Palma'),
(54, 4, 'La Reina'),
(55, 4, 'Las Vueltas'),
(56, 4, 'Nueva Concepción'),
(57, 4, 'Nueva Trinidad'),
(58, 4, 'Nombre de Jesus'),
(59, 4, 'Ojos de Agua'),
(60, 4, 'Potonico'),
(61, 4, 'San Antonio de la Cruz'),
(62, 4, 'San Antonio Los Ranchos'),
(63, 4, 'San Fernando'),
(64, 4, 'San Francisco Lempa'),
(65, 4, 'San Francisco Morazan'),
(66, 4, 'San Ignacio'),
(67, 4, 'San Isidro Labrador'),
(68, 4, 'San Jose Cancasque'),
(69, 4, 'San Jose Las Flores'),
(70, 4, 'San Luis del Carmen'),
(71, 4, 'San Miguel de Mercedes'),
(72, 4, 'San Rafael'),
(73, 4, 'Santa Rita'),
(74, 4, 'Tejutla'),
(75, 5, 'Candelaria'),
(76, 5, 'Cojutepeque'),
(77, 5, 'El Carmen'),
(78, 5, 'El Rosario'),
(79, 5, 'Monte San Juan'),
(80, 5, 'Oratorio de Concepción'),
(81, 5, 'San Bartolom? Perulapia'),
(82, 5, 'San Cristobal'),
(83, 5, 'San Jose Guayabal'),
(84, 5, 'San Pedro Perulapan'),
(85, 5, 'San Rafael Cedros'),
(86, 5, 'San Ramón'),
(87, 5, 'Santa Cruz Analquito'),
(88, 5, 'Santa Cruz Michapa'),
(89, 5, 'Suchitoto'),
(90, 5, 'Tenancingo'),
(91, 6, 'Aguilares'),
(92, 6, 'Apopa'),
(93, 6, 'Ayutuxtepeque'),
(94, 6, 'Cuscatancingo'),
(95, 6, 'Delgado'),
(96, 6, 'El Paisnal'),
(97, 6, 'Guazapa'),
(98, 6, 'Ilopango'),
(99, 6, 'Mejicanos'),
(100, 6, 'Nejapa'),
(101, 6, 'Panchimalco'),
(102, 6, 'Rosario de Mora'),
(103, 6, 'San Marcos'),
(104, 6, 'San Martín'),
(105, 6, 'San Salvador'),
(106, 6, 'Santiago Texacuangos'),
(107, 6, 'Santo Tomas'),
(108, 6, 'Soyapango'),
(109, 6, 'Tonacatepeque'),
(110, 7, 'Antiguo Cuscatlan'),
(111, 7, 'Chiltiupan'),
(112, 7, 'Ciudad Arce'),
(113, 7, 'Colón'),
(114, 7, 'Comasagua'),
(115, 7, 'Huizucar'),
(116, 7, 'Jayaque'),
(117, 7, 'Jicalapa'),
(118, 7, 'La Libertad'),
(119, 7, 'Santa Tecla'),
(120, 7, 'Nuevo Cuscatlan'),
(121, 7, 'San Juan Opico'),
(122, 7, 'Quezaltepeque'),
(123, 7, 'Sacacoyo'),
(124, 7, 'San Jose Villanueva'),
(125, 7, 'San Matias'),
(126, 7, 'San Pablo Tacachico'),
(127, 7, 'Talnique'),
(128, 7, 'Tamanique'),
(129, 7, 'Teotepeque'),
(130, 7, 'Tepecoyo'),
(131, 7, 'Zaragoza'),
(132, 8, 'Apastepeque'),
(133, 8, 'Guadalupe'),
(134, 8, 'San Cayetano Istepeque'),
(135, 8, 'San Esteban Catarina'),
(136, 8, 'San Ildefonso'),
(137, 8, 'San Lorenzo'),
(138, 8, 'San Sebastian'),
(139, 8, 'San Vicente'),
(140, 8, 'Santa Clara'),
(141, 8, 'Santo Domingo'),
(142, 8, 'Tecoluca'),
(143, 8, 'Tepetitan'),
(144, 8, 'Verapaz'),
(145, 9, 'Cuyultitlan'),
(146, 9, 'El Rosario'),
(147, 9, 'Jerusalen'),
(148, 9, 'Mercedes La Ceiba'),
(149, 9, 'Olocuilta'),
(150, 9, 'Paraiso de Osorio'),
(151, 9, 'San Antonio Masahuat'),
(152, 9, 'San Emigdio'),
(153, 9, 'San Francisco Chinameca'),
(154, 9, 'San Juan Nonualco'),
(155, 9, 'San Juan Talpa'),
(156, 9, 'San Juan Tepezontes'),
(157, 9, 'San Luis Talpa'),
(158, 9, 'San Luis La Herradura'),
(159, 9, 'San Miguel Tepezontes'),
(160, 9, 'San Pedro Masahuat'),
(161, 9, 'San Pedro Nonualco'),
(162, 9, 'San Rafael Obrajuelo'),
(163, 9, 'Santa Maria Ostuma'),
(164, 9, 'Santiago Nonualco'),
(165, 9, 'Tapalhuaca'),
(166, 9, 'Zacatecoluca'),
(167, 10, 'Cinquera'),
(168, 10, 'Dolores'),
(169, 10, 'Guacotecti'),
(170, 10, 'Ilobasco'),
(171, 10, 'Jutiapa'),
(172, 10, 'San Isidro'),
(173, 10, 'Sensuntepeque'),
(174, 10, 'Tejutepeque'),
(175, 10, 'Victoria'),
(176, 11, 'Alegria'),
(177, 11, 'Berlín'),
(178, 11, 'California'),
(179, 11, 'Concepción Batres'),
(180, 11, 'El Triunfo'),
(181, 11, 'Ereguayquín'),
(182, 11, 'Estanzuelas'),
(183, 11, 'Jiquilisco'),
(184, 11, 'Jucuapa'),
(185, 11, 'Jucuaran'),
(186, 11, 'Mercedes Umana'),
(187, 11, 'Nueva Granada'),
(188, 11, 'Ozatlan'),
(189, 11, 'Puerto El Triunfo'),
(190, 11, 'San Agustín'),
(191, 11, 'San Buenaventura'),
(192, 11, 'San Dionisio'),
(193, 11, 'San Francisco Javier'),
(194, 11, 'Santa Elena'),
(195, 11, 'Santa Maria'),
(196, 11, 'Santiago de Maria'),
(197, 11, 'Tecapan'),
(198, 11, 'Usulutan'),
(199, 12, 'Carolina'),
(200, 12, 'Chapeltique'),
(201, 12, 'Chinameca'),
(202, 12, 'Chirilagua'),
(203, 12, 'Ciudad Barrios'),
(204, 12, 'Comacaran'),
(205, 12, 'El Transito'),
(206, 12, 'Lolotique'),
(207, 12, 'Moncagua'),
(208, 12, 'Nueva Guadalupe'),
(209, 12, 'Nuevo Eden de San Juan'),
(210, 12, 'Quelepa'),
(211, 12, 'San Antonio del Mosco'),
(212, 12, 'San Gerardo'),
(213, 12, 'San Jorge'),
(214, 12, 'San Luis de la Reina'),
(215, 12, 'San Miguel'),
(216, 12, 'San Rafael Oriente'),
(217, 12, 'Sesori'),
(218, 12, 'Uluazapa'),
(219, 13, 'Arambala'),
(220, 13, 'Cacaopera'),
(221, 13, 'Chilanga'),
(222, 13, 'Corinto'),
(223, 13, 'Delicias de Concepción'),
(224, 13, 'El Divisadero'),
(225, 13, 'El Rosario'),
(226, 13, 'Gualococti'),
(227, 13, 'Guatajiagua'),
(228, 13, 'Joateca'),
(229, 13, 'Jocoaitique'),
(230, 13, 'Jocoro'),
(231, 13, 'Lolotiquillo'),
(232, 13, 'Meanguera'),
(233, 13, 'Osicala'),
(234, 13, 'Perquín'),
(235, 13, 'San Carlos'),
(236, 13, 'San Fernando'),
(237, 13, 'San Francisco Gotera'),
(238, 13, 'San Isidro'),
(239, 13, 'San Simón'),
(240, 13, 'Sensembra'),
(241, 13, 'Sociedad'),
(242, 13, 'Torola'),
(243, 13, 'Yamabal'),
(244, 13, 'Yoloaiquín'),
(245, 14, 'La Unión'),
(246, 14, 'San Alejo'),
(247, 14, 'Yucuaiquín'),
(248, 14, 'Conchagua'),
(249, 14, 'Intipuca'),
(250, 14, 'San Jose'),
(251, 14, 'El Carmen'),
(252, 14, 'Yayantique'),
(253, 14, 'Bolivar'),
(254, 14, 'Meanguera del Golfo'),
(255, 14, 'Santa Rosa de Lima'),
(256, 14, 'Pasaquina'),
(257, 14, 'Anamoros'),
(258, 14, 'Nueva Esparta'),
(259, 14, 'El Sauce'),
(260, 14, 'Concepción de Oriente'),
(261, 14, 'Poloros'),
(262, 14, 'Lislique');
