DROP DATABASE IF EXISTS ci_formulario_ajax;
CREATE DATABASE IF NOT EXISTS ci_formulario_ajax DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE ci_formulario_ajax;

DROP TABLE IF EXISTS mensajes;
CREATE TABLE IF NOT EXISTS mensajes(
	id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL COLLATE utf8_spanish_ci,
	email VARCHAR(100) NOT NULL,
	asunto VARCHAR(200) NOT NULL COLLATE utf8_spanish_ci,
	mensaje TEXT DEFAULT NULL COLLATE utf8_spanish_ci,
	hora TIME DEFAULT NULL,
	fecha DATE DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
